name: CI

on: [push]

jobs:
  build:
    container: mcr.microsoft.com/windows:1903
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Run setup script
      run: .\setup.ps1
