name: CI

on: [push]

jobs:
  build:
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Run setup script
      run: |
         Set-Alias -Name wget -Value Invoke-WebRequest
         .\setup.ps1
      shell: pwsh
